### ISSUE TITLE
Bad address

### ISSUE THREAD

**Issue by PrabhakarTayenjam** [MJjainam/falseSharing#1]
Why is the array[1] bad and array[99] good?

**Comment by MJjainam** [comment]
We are starting parallel computation from array[0] and array[1]. Both elements are close to each other so the false sharing will be higher. (That's why the name bad)

In the second case where the parallel computation is happening from either end of the array, the false sharing will much lesser (That's why the name good).

Refer the blog for more details - https://parallelcomputing2017.wordpress.com/2017/03/17/understanding-false-sharing/

**Comment by PrabhakarTayenjam** [comment]
What will be the minimum index that will not cause false sharing?

**Comment by MJjainam** [comment]
That is up to the machine hardware on how big are the cache blocks.

**Comment by MJjainam** [comment]
That is up to the machine hardware on how big is the cache block size.
